# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'LLFormer_LOL'

# Optimization arguments.
OPTIM:
  BATCH: 12
  EPOCHS: 3000
  # EPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: '/root/LOL_init/our485'       # path to training data
  VAL_DIR: '/root/LOL_init/eval15' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
